---

- name: deploy site package script
  ansible.builtin.template:
    src: '{{ lmod_site_package }}'
    dest: '{{ __lmod_install_dir }}/libexec/SitePackage.lua'
    owner: root
    group: root
    mode: '0644'

...
