---

dependency:
  name: galaxy

driver:
  name: docker

platforms:

  - name: debian-bullseye
    image: ghcr.io/idiv-biodiversity/ansible-molecule-debian-bullseye:latest
    pre_build_image: yes
    groups:
      - nosudo

  - name: debian-bookworm
    image: ghcr.io/idiv-biodiversity/ansible-molecule-debian-bookworm:latest
    pre_build_image: yes
    groups:
      - nosudo

  - name: rockylinux-8
    image: ghcr.io/idiv-biodiversity/ansible-molecule-rockylinux-8:latest
    pre_build_image: yes
    groups:
      - nosudo

  - name: rockylinux-9
    image: ghcr.io/idiv-biodiversity/ansible-molecule-rockylinux-9:latest
    pre_build_image: yes
    groups:
      - nosudo

  - name: ubuntu-focal
    image: ghcr.io/idiv-biodiversity/ansible-molecule-ubuntu-focal:latest
    pre_build_image: yes
    groups:
      - nosudo

  - name: ubuntu-jammy
    image: ghcr.io/idiv-biodiversity/ansible-molecule-ubuntu-jammy:latest
    pre_build_image: yes
    groups:
      - nosudo

  - name: ubuntu-noble
    image: ghcr.io/idiv-biodiversity/ansible-molecule-ubuntu-noble:latest
    pre_build_image: yes
    groups:
      - nosudo

provisioner:
  name: ansible
  inventory:
    group_vars:
      nosudo:
        ansible_become_method: su

verifier:
  name: ansible

...
